language: java
before_install:
 - chmod +x gradlew

install: gradle assemble

build: gradle build

deploy:
  - provider: script
    script: sh deploy.sh $repo_password
    on:
       branch: release

branches:
  only:
  - master
  - development
  - /^feature.*$/
  - /^release.*$/
